services:
    laravel.test:
        build:
        # This means PHP 8.5
        # We might need to downgrade to match the server.
            # context: ./docker/8.5
            context: ./docker/8.4
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        # Does this also mean PHP 8.5?
        # Yes, I think it does because vendor/laravel/sail/runtimes contains directories for 8.5, 8.4, ... 8.0.
        # Or does it?
        # Docker started to pull a new image when I changed to sail-8.4, but that seems reasonable.
        # Laravel docs say this is just a name for the image and it doesn't inform the version of PHP used.
        # shrug?
        image: sail-8.5/app
        # image: sail-8.4/app
        extra_hosts:
            - 'host.docker.internal:host-gateway'
        ports:
            - '${APP_PORT:-80}:80'
            - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
            XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
            XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
    mysql:
        # we can change this MariaDB if needed
        image: 'mysql:8.4'
        ports:
            - '${FORWARD_DB_PORT:-3306}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
            MYSQL_EXTRA_OPTIONS: '${MYSQL_EXTRA_OPTIONS:-}'
        volumes:
            - 'sail-mysql:/var/lib/mysql'
            - './docker/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh'
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s
    # add phpMyAdmin to simplify importing CSV to DB
    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin:latest'
        links:
            - mysql:mysql
        ports:
            - '${PMA_PORT:-8080}:80'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            PMA_HOST: mysql
        networks:
            - sail
        depends_on:
            - mysql
    # add mailhog to simplify mail testing
    mailhog:
        image: mailhog/mailhog:latest
        container_name: mailhog
        restart: always
        ports:
            - "1025:1025" # SMTP server port
            - "8025:8025" # Web UI port
        logging:
            driver: 'none' # Optional: disables verbose MailHog container logs
        networks:
            - sail
networks:
    sail:
        driver: bridge
volumes:
    sail-mysql:
        driver: local
