# Laravel deployment configuration file
# Define values needed to deploy a specific Laravel site.

# SITE_NAME is the name of the root project directory on the server which 
# houses the "releases" directory and other persistent, shared resources such # as .env and storage
# E.g., /srv/www/htdocs/${SITE_NAME}
SITE_NAME=""
# BRANCH is the branch that gets checked out from the repo specified by REPO_URL.
# E.g., development, qa, main
BRANCH=""
# the repo from which to checkout the branch specified by BRANCH
REPO_URL=""